<?php
/** @var \Magento\Catalog\Block\Product\View\Description $block */
/** @var \MageSuite\ProductSymbols\ViewModel\Symbol\CmsBlockList $viewModel */
$product = $block->getProduct();
$viewModel = $block->getSymbolViewModel();
?>
<?php if ($product) : ?>
    <?php foreach ($viewModel->getList($product) as $cmsBlock): ?>
        <?= /* @noEscape */ $cmsBlock ?>
    <?php endforeach; ?>
<?php endif; ?>
